name: Test Workflow
description: Workflow that runs tests when a pull request is opened
on:
  pull_request:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate repository visualization
        uses: githubocto/repo-visualizer@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
